import { defaults } from './defaults.js'

export const g1847ae = {
  ...defaults,

  maturity: 2, titleId: 'g1847ae',
  gameInfo: '• Incremental capitalization, 50% float, sequential corp founding order • Investor shares (from privates) auto-exchange into corp shares at 5+5 phase • LFK private company earns 10% of every train purchase price in the game • Non-standard shares: some corps have 20/10/20/10/10/10/20 splits • 7 corps + LFK entity, English auction for 10 privates including presidency grants • 2D grid market (7x16), sell moves down (blocked), must sell in blocks • 8 phases with paired trains (3/3+3, 4/4+4, 5/5+5, 6E/6+6) • M8,000 bank, 3-5 players, Pfalz Germany setting',
  implemented: 'Shares • Dividends • Non-standard shares • Investor conversion (config)',
  title: '1847 AE',
  subtitle: 'Pfalz — Anniversary Edition',
  designer: 'Wolfram Janich',
  location: 'Pfalz, Germany',
  minPlayers: 3,
  maxPlayers: 5,

  bankCash: 8000,
  startingCash: { 3: 500, 4: 390, 5: 320 },
  certLimit: { 3: 16, 4: 12, 5: 9 },
  currencyFormat: 'M',

  capitalization: 'incremental',
  floatPercent: 50,
  sellBuyOrder: 'sell_buy',
  sellMovement: 'down_block',
  sellAfter: 'operate',
  mustSellInBlocks: true,

  market: [
    ['','','','','130','150','170','190','210','230','255','285','315','350','385','420'],
    ['','','98','108','120','135','150','170','190','210','235','260','285','315','350','385'],
    ['82','86p','92','100p','110','125','140','155','170','190','210','235','260','290','320'],
    ['78','84p','88','94','104','112','125','140','155','170','190','215'],
    ['72','80p','86','90','96','104','115','125','140'],
    ['62','74p','82','88','92','98','105'],
    ['50','66p','76','84','90'],
  ],

  phases: [
    { name: '3', trainLimit: 4, tiles: ['yellow'], operatingRounds: 1 },
    { name: '3+3', on: '3+3', trainLimit: 4, tiles: ['yellow'], operatingRounds: 1 },
    { name: '4', on: '4', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '4+4', on: '4+4', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '5', on: '5', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 3 },
    { name: '5+5', on: '5+5', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 3 },
    { name: '6E', on: '6E', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 3 },
    { name: '6+6', on: '6+6', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 3 },
  ],

  trains: [
    { name: '3', distance: 3, price: 150, rustsOn: '4+4', num: 3 },
    { name: '3+3', distance: 3, price: 300, rustsOn: '5+5', num: 2 },
    { name: '4', distance: 4, price: 300, rustsOn: '6+6', num: 2 },
    { name: '4+4', distance: 4, price: 500, num: 1 },
    { name: '5', distance: 5, price: 450, num: 2 },
    { name: '5+5', distance: 5, price: 550, num: 1, events: ['must_exchange_investor_companies'] },
    { name: '6E', distance: 6, price: 550, num: 1 },
    { name: '6+6', distance: 6, price: 700, num: 9 },
  ],

  corporations: [
    { sym: 'LFK', name: 'Locomotive Firm Krauss & Co.', tokens: [], color: '#fff', textColor: '#000', floatPercent: 100, shares: [100],
      desc: 'Private company. Revenue = 10% of train purchase cost.' },
    { sym: 'L', name: 'Pfälzische Ludwigsbahn', tokens: [0,60,80,100], color: '#4682b4', coordinates: 'F18', floatPercent: 50 },
    { sym: 'Saar', name: 'Saarbrücker Eisenbahn', tokens: [0,60,80,100], color: '#ff4040', coordinates: 'H6', floatPercent: 50,
      shares: [20,10,10,10,10,10,10,20] },
    { sym: 'HLB', name: 'Hessische Ludwigsbahn', tokens: [0,0,80,100], color: '#dda0dd', textColor: '#000', floatPercent: 50,
      shares: [20,10,10,10,10,10,10,20], desc: 'Two home stations. May not start until Saar floats.' },
    { sym: 'NDB', name: 'Neustadt-Dürkheimer Bahn', tokens: [0,60], color: '#61b229', floatPercent: 50,
      shares: [20,10,20,10,10,10,20], desc: 'May not start until HLB floats.' },
    { sym: 'M', name: 'Pfälzische Maximiliansbahn', tokens: [0,60,80], color: '#fafa37', textColor: '#000', coordinates: 'H16', floatPercent: 50,
      shares: [20,10,10,10,10,10,10,20], desc: 'May not start until HLB floats.' },
    { sym: 'N', name: 'Pfälzische Nordbahn', tokens: [0,60,80], color: '#ffc04d', textColor: '#000', coordinates: 'F12', floatPercent: 50,
      shares: [20,10,20,10,10,10,20], desc: 'May not start until HLB floats.' },
    { sym: 'RNB', name: 'Rhein-Nahe-Bahn', tokens: [0,60,80], color: '#ffc0cb', textColor: '#000', coordinates: 'C13', floatPercent: 50,
      shares: [20,10,20,10,10,10,20], desc: 'May not start until HLB floats.' },
  ],

  pregame: [{ id: 'auction', label: 'Private Auction', type: 'english' }],

  companies: [
    { sym: 'PLP', name: 'Pfälzische Ludwigsbahn presidency', value: 172, revenue: 0,
      desc: 'Comes with two shares of Pfälzische Ludwigsbahn (L). Closes immediately.' },
    { sym: 'SPR', name: 'Saarbrücker Private Railway', value: 190, revenue: 15,
      desc: 'Comes with president\'s certificate of Saar. Cannot be sold to a corp. Closes when Saar buys first train.' },
    { sym: 'LFKC', name: 'Locomotive Firm Krauss & Co.', value: 130, revenue: 0,
      desc: 'Comes with the President\'s certificate of LFK.' },
    { sym: 'R', name: 'Rammelsbach', value: 150, revenue: 30,
      desc: 'Revenue increases to M50 when tile laid in E9. May be sold to corp for M100-200. Never closes.' },
    { sym: 'K', name: 'Königsbach', value: 110, revenue: 5,
      desc: 'Corp may close to place free yellow tile on mountain hex. Comes with share of L. Closes phase 6E.' },
    { sym: 'H', name: 'Hochstätten', value: 160, revenue: 15,
      desc: 'Corp may close to place free yellow tile on mountain hex. Comes with share of L. Closes phase 6E.' },
    { sym: 'W', name: 'Weidenthal', value: 135, revenue: 10,
      desc: 'Corp may close to place token at half price. Comes with share of L. Closes phase 6E.' },
    { sym: 'MNR', name: 'Main-Neckar-Railway', value: 90, revenue: 20,
      desc: 'Exchange for Investor share of HLB. Auto-exchanged phase 5+5. Cannot be sold to corp.' },
    { sym: 'SCR', name: 'Saarland Coal Mines', value: 75, revenue: 15,
      desc: 'Exchange for Investor share of Saar. Auto-exchanged phase 5+5. Cannot be sold to corp.' },
    { sym: 'VIW', name: 'Völklinger Iron Works', value: 85, revenue: 20,
      desc: 'Exchange for Investor share of Saar. Auto-exchanged phase 5+5. Cannot be sold to corp.' },
  ],
}
