import { defaults } from './defaults.js'

export const g1871 = {
  ...defaults,
  maturity: 2, titleId: 'g1871',
  gameInfo: '• 7 mainline corps + 6 branch lines + PEIR national railway • Full capitalization, 60% float, unlimited bank, half pay allowed • English auction for 12 privates including concessions and share grants • Salvage value on 2+/3+/4+ trains ($20/$30/$60 returned on rust) • 2D grid market (7x15), sell moves down per share, first-to-pass SR order • 10 phases (2H through D), many train tiers with rapid rusting • PEIR has 5x20% shares and starts with $200 from King\'s Mail private • 3-4 players only, Prince Edward Island setting', title: '1871', subtitle: 'The Old Prince', designer: 'Lucas Boyd',
  location: 'Prince Edward Island', minPlayers: 3, maxPlayers: 4,
  bankCash: 99999, startingCash: { 3: 580, 4: 480 }, certLimit: { 3: 20, 4: 16 },
  currencyFormat: '$', capitalization: 'full', floatPercent: 60, sellBuyOrder: 'sell_buy', sellMovement: 'down_block', halfPay: true, nextSRPlayerOrder: 'first_to_pass',
  market: [
    ['','','111','122','136','152','170','190','215','240','270','300','330','360','400B'],
    ['88','92','100','110','121','133','146','160','180','200','225','250','280'],
    ['82','86','93','101','111','123','137','152','167','185','203'],
    ['78','80p','86','94','102','112','122'],
    ['71','74x','79','84','89','94'],
    ['60','65z','69','73','78'],
    ['55','58w','61','65'],
  ],
  phases: [
    { name: '2H', trainLimit: 4, tiles: ['yellow'], operatingRounds: 1 },
    { name: '3H', on: '3H', trainLimit: 4, tiles: ['yellow'], operatingRounds: 1 },
    { name: '4H', on: '4H', trainLimit: 4, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '5H', on: '5H', trainLimit: 4, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '6H', on: '6H', trainLimit: 4, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '2+', on: '2+', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '3+', on: '3+', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '4+', on: '4+', trainLimit: 3, tiles: ['yellow','green','brown'], operatingRounds: 3 },
    { name: '7', on: '7', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 3 },
    { name: 'D', on: 'D', trainLimit: 2, tiles: ['yellow','green','brown','gray'], operatingRounds: 3 },
  ],
  trains: [
    { name: '2H', distance: 2, price: 80, rustsOn: '5H', num: 4 },
    { name: '3H', distance: 3, price: 100, rustsOn: '6H', num: 3 },
    { name: '4H', distance: 4, price: 120, rustsOn: '2+', num: 3 },
    { name: '5H', distance: 5, price: 160, rustsOn: '3+', num: 3 },
    { name: '6H', distance: 6, price: 180, rustsOn: '4+', num: 2 },
    { name: '2+', distance: 2, price: 220, rustsOn: '7', num: 4, salvageValue: 20 },
    { name: '3+', distance: 3, price: 240, rustsOn: 'D', num: 3, salvageValue: 30 },
    { name: '4+', distance: 4, price: 200, rustsOn: 'D', num: 2, salvageValue: 60 },
    { name: '7', distance: 7, price: 500, num: 4 },
    { name: 'D', distance: 999, price: 600, num: 20 },
  ],
  corporations: [
    { sym: 'So', name: 'Souris', tokens: [0,80,80,80], color: '#0a0a0a', coordinates: 'T12' },
    { sym: 'A', name: 'Alberton', tokens: [0,80,80,80], color: '#b58168', textColor: '#000', coordinates: 'D6' },
    { sym: 'MS', name: 'Mount Stewart', tokens: [0,80,80,80], color: '#fcea18', textColor: '#000', coordinates: 'M13' },
    { sym: 'MR', name: 'Murray River', tokens: [0,80,80,80], color: '#37b2e2', textColor: '#000', coordinates: 'Q21' },
    { sym: 'S', name: 'Summerside', tokens: [0,80,80,80], color: '#7bb137', textColor: '#000', coordinates: 'F14' },
    { sym: 'Gt', name: 'Georgetown', tokens: [0,80,80,80], color: '#9a9a9d', textColor: '#000', coordinates: 'R16' },
    { sym: 'C', name: 'Charlottetown', tokens: [0,80,80,80], color: '#a60a3d', coordinates: 'L16' },
    { sym: 'PEIR', name: 'Prince Edward Island Railway', tokens: [0,0,0,0,0], color: '#ec767c', textColor: '#000', shares: [20,20,20,20,20], type: 'national' },
    { sym: 'CB', name: 'Cornwall Branch', tokens: [0,80,80,80], color: '#baa4cb', textColor: '#000', type: 'branch' },
    { sym: 'SB', name: 'Stratford Branch', tokens: [0,80,80,80], color: '#bf4da5', type: 'branch' },
    { sym: 'MB', name: 'Morel Branch', tokens: [0,80,80,80], color: '#0a70b3', type: 'branch' },
    { sym: 'BB', name: 'Belfast Branch', tokens: [0,80,80,80], color: '#eb6f0e', textColor: '#000', type: 'branch' },
    { sym: 'WB', name: 'Wellington Branch', tokens: [0,80,80,80], color: '#bdbd00', textColor: '#000', type: 'branch' },
    { sym: 'HRB', name: 'Hunter River Branch', tokens: [0,80,80,80], color: '#008f4f', type: 'branch' },
  ],

  pregame: [{ id: 'auction', label: 'Private Auction', type: 'english' }],

  companies: [
    { sym: 'MC', name: 'Merchants and Co.', value: 40, revenue: 5, desc: 'Exchange for Shortline exchange share during SR.' },
    { sym: 'VR', name: 'Vernon River Bridge Company', value: 40, revenue: 5, desc: 'Blocks N18. Exchange for Shortline exchange share.' },
    { sym: 'IB', name: 'Ice Boat Shipping', value: 40, revenue: 5, minPlayers: 4, desc: 'Exchange for market share of any non-ML/SL corp.' },
    { sym: 'RA', name: 'Royal Agricultural Society', value: 110, revenue: 10, desc: 'Comes with a Mainline share.' },
    { sym: 'RF', name: 'Railcar Ferry', value: 120, revenue: 15, desc: 'Comes with a Mainline share.' },
    { sym: 'SB', name: 'Shipbuilding', value: 90, revenue: 15, desc: 'Exchange for Shortline exchange share.' },
    { sym: 'HSE', name: 'Hunslet Steam Engine', value: 110, revenue: 20, desc: 'Sell to corp for $1-$200. Close to buy train from supply.' },
    { sym: 'ML', name: 'Mainline Concession', value: 160, revenue: 20, desc: 'Comes with 20% president cert. Closes when Mainline operates.' },
    { sym: 'SBC', name: 'Schreiber and Burpee Construction', value: 100, revenue: 30, desc: 'Comes with yellow straight tile.' },
    { sym: 'SLC', name: 'Short Line Concession', value: 160, revenue: 30, desc: 'Comes with 20% president cert of Shortline.' },
    { sym: 'UB', name: 'Union Bank', value: 120, revenue: 0, desc: 'Comes with 1 Mainline + 1 Random share. Owner may buy 1 share per SR.' },
    { sym: 'KM', name: "The King's Mail", value: 0, revenue: 80, desc: 'Always assigned to PEIR. PEIR starts with $200. Closes on 4+.' },
  ],
}
