import { defaults } from './defaults.js'

export const g1880 = {
  ...defaults,

  maturity: 2, testQuality: 1, titleId: 'g1880',
  gameInfo: '• Building permits (A/B/C/D) gate which corps can lay track in each phase • Communist takeover at phase B3 closes stock market, reopens at phase C2 • 14 corps with 3 tokens each, 20% float, sell/buy stock rounds • 2D grid market (9x14) with letter-coded columns, 80% pool limit • 8 privates drafted, P6 grants BCR director cert and is the kingmaker pick • 11 phases (A1 through D3), float percent increases as phases advance • ¥37,860 bank, game ends after first 8-train triggers one more full OR set • 3-7 players, sweet spot 4-5p, long complex game (4-6 hours)',
  specialties: 'Chinese Eastern Railway • Foreign investors • Token cost doubling event',
  implemented: 'Shares • Dividends • Building permits (config) • Communist takeover (config)',
  title: '1880',
  subtitle: 'China',
  designer: 'Helmut Ohley, Leonhard Orgler',
  location: 'China',
  minPlayers: 3,
  maxPlayers: 7,

  bankCash: 37860,
  startingCash: { 3: 600, 4: 480, 5: 400, 6: 340, 7: 300 },
  certLimit: { 3: 20, 4: 16, 5: 14, 6: 12, 7: 11 },
  currencyFormat: '¥',

  sellBuyOrder: 'sell_buy',
  sellMovement: 'down_per_10',
  marketShareLimit: 80,
  floatPercent: 20,
  ebuyPresSwap: false,
  ebuyDepotCheapest: false,

  gameEndCheck: { finalTrain: 'one_more_full_or_set' },

  market: [
    ['','','100','105','110','115B','120B','125B','130W','140W','150X','160X','180Y','200Z'],
    ['','85','95','100p','105','110B','115B','120B','125W','135W','145X','155X','170Y','190Y'],
    ['70','80','90','95','100','105B','110B','115B','120W','130W','140X','150X','165Y','180Y'],
    ['65','75','85','90p','95','100B','105B','110B','115W','125W','135X','145X'],
    ['60','70','80','85','90','95B','100B','105B','110W','120W'],
    ['55','65','75','80p','85','90B','95B','100B'],
    ['50','60','70','75','80','85B','90B'],
    ['45','55','65','70p','75','80B'],
    ['40','50','60','65','70'],
  ],

  phases: [
    { name: 'A1', trainLimit: 4, tiles: ['yellow'], operatingRounds: 1 },
    { name: 'A2', on: '2+2', trainLimit: 4, tiles: ['yellow'], operatingRounds: 1 },
    { name: 'B1', on: '3', trainLimit: 4, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: 'B2', on: '3+3', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: 'B3', on: '4', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: 'C1', on: '4+4', trainLimit: 3, tiles: ['yellow','green','brown'], operatingRounds: 2 },
    { name: 'C2', on: '6', trainLimit: 3, tiles: ['yellow','green','brown'], operatingRounds: 2 },
    { name: 'C3', on: '6E', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 2 },
    { name: 'D1', on: '8', trainLimit: 2, tiles: ['yellow','green','brown','gray'], operatingRounds: 2 },
    { name: 'D2', on: '8E', trainLimit: 2, tiles: ['yellow','green','brown','gray'], operatingRounds: 2 },
    { name: 'D3', on: '10', trainLimit: 2, tiles: ['yellow','green','brown','gray'], operatingRounds: 2 },
  ],

  trains: [
    { name: '2', distance: 2, price: 100, rustsOn: '4', num: 10 },
    { name: '2+2', distance: 2, price: 180, rustsOn: '4+4', num: 5 },
    { name: '3', distance: 3, price: 180, rustsOn: '6', num: 5, events: ['float_30','permit_b'] },
    { name: '3+3', distance: 3, price: 300, rustsOn: '6E', num: 5 },
    { name: '4', distance: 4, price: 300, rustsOn: '8', num: 5, events: ['float_40','communist_takeover'] },
    { name: '4+4', distance: 4, price: 450, rustsOn: '8E', num: 5, events: ['permit_c'] },
    { name: '6', distance: 6, price: 600, num: 5, events: ['float_60','stock_exchange_reopens'] },
    { name: '6E', distance: 6, price: 700, num: 5 },
    { name: '8', distance: 8, price: 800, num: 2, events: ['permit_d','token_cost_doubled','signal_end_game'] },
    { name: '8E', distance: 8, price: 900, num: 2 },
    { name: '10', distance: 10, price: 1000, num: 10 },
    { name: '2P', distance: 2, price: 250, num: 10, availableOn: 'C2' },
  ],

  corporations: [
    { sym: 'JHA', name: 'Jingha Railway', tokens: [0,40,100], color: '#BA6128', coordinates: 'F8' },
    { sym: 'JHU', name: 'Jinghu Railway', tokens: [0,40,100], color: '#000000', coordinates: 'F8' },
    { sym: 'JGG', name: 'Jingguang Railway', tokens: [0,40,100], color: '#534074', coordinates: 'F8' },
    { sym: 'JLR', name: 'Jinglan Railway', tokens: [0,40,100], color: '#008A8B', coordinates: 'F8' },
    { sym: 'BZU', name: 'Binzhou Railway', tokens: [0,40,100], color: '#9D8359', coordinates: 'B8' },
    { sym: 'LHR', name: 'Longhai Railway', tokens: [0,40,100], color: '#004294', coordinates: 'J2' },
    { sym: 'SCR', name: 'Schichang Railway', tokens: [0,40,100], color: '#282F1A', coordinates: 'N12' },
    { sym: 'CKR', name: 'Chengkun Railway', tokens: [0,40,100], color: '#507EAE', coordinates: 'O5' },
    { sym: 'BCR', name: 'Baocheng Railway', tokens: [0,40,100], color: '#94121D', coordinates: 'M3' },
    { sym: 'NXR', name: 'Ningxi Railway', tokens: [0,40,100], color: '#A83B5B', coordinates: 'J6' },
    { sym: 'HKR', name: 'Hukun Railway', tokens: [0,40,100], color: '#40743A', coordinates: 'K15' },
    { sym: 'NJR', name: 'Nanjiang Railway', tokens: [0,40,100], color: '#452518', coordinates: 'K13' },
    { sym: 'QSR', name: 'Qinshen Railway', tokens: [0,40,100], color: '#B3932C', coordinates: 'D12' },
    { sym: 'WNR', name: 'Wunan Railway', tokens: [0,40,100], color: '#A4391F', coordinates: 'L10' },
  ],

  pregame: [{ id: 'draft', label: 'Draft', type: 'draft' }],

  companies: [
    { sym: 'P0', name: 'Woosong Railway', value: 5, revenue: 0,
      desc: 'Owner receives one-off payment of ¥40/70/100 when last 2+2/3/3+3 train is purchased.' },
    { sym: 'P1', name: 'Kaiping Railway', value: 10, revenue: 5,
      desc: 'No special power.' },
    { sym: 'P2', name: 'Yanda Ferry Company', value: 25, revenue: 10,
      desc: 'The owner may use all ferries for free with all their companies.' },
    { sym: 'P3', name: 'Taiwan Western Line', value: 45, revenue: 15,
      desc: 'For the owner, the value of Taiwan is +¥20 with all their companies.' },
    { sym: 'P4', name: 'Chinese Rivers Ferry Companies', value: 70, revenue: 20,
      desc: 'Reduce the cost of laying a tile in a river hex by ¥20 for all their companies.' },
    { sym: 'P5', name: 'Jeme Tien Yow Engineer Office', value: 100, revenue: 25,
      desc: 'Building permit for Phase D for one of their companies.' },
    { sym: 'P6', name: 'Imperial Qing Government', value: 160, revenue: 0,
      desc: 'The owner receives the 20% Director\'s Certificate of the BCR. BCR may always lay 2 yellow tiles.' },
    { sym: 'P7', name: 'Rocket of China', value: 50, revenue: 0,
      desc: 'The owner may exchange for a currently available train for one of their companies. Forced exchange into second 4-train.' },
  ],
}
