import { defaults } from './defaults.js'

export const g18usa = {
  ...defaults,
  maturity: 2, titleId: 'g18usa',
  gameInfo: '• Incremental cap, 20% float • Resource markers (coal, ore, oil) • Subsidy privates • 2-7 players', title: '18USA', subtitle: 'The Railroads Come of Age', designer: 'Edward Reece, Mark Hendrickson, Shawn Fox',
  location: 'United States', minPlayers: 2, maxPlayers: 7,
  bankCash: 99999, startingCash: { 2: 630, 3: 420, 4: 315, 5: 300, 6: 250, 7: 225 },
  certLimit: { 2: 32, 3: 21, 4: 16, 5: 16, 6: 13, 7: 11 },
  currencyFormat: '$', capitalization: 'incremental', floatPercent: 20, sellBuyOrder: 'sell_buy', halfPay: true,
  market: [
    ['0l','0a','0a','0a','42','44','46','48','50p','53s','56p','59p','62p','66p','70p','74s','78p','82p','86p','90p','95p','100p','105p','110p','115p','120s','127p','135p','142p','150p','157p','165p','172p','180p','190p','200p','210','220','230','240','250','260','270','285','300','315','330','345','360','375','390','405','420','440','460','480','500','520','540','560','580','600','625','650','675','700','725','750','775','800'],
  ],
  phases: [
    { name: '2', trainLimit: 4, tiles: ['yellow'], operatingRounds: 2 },
    { name: '2+', on: '2+', trainLimit: 4, tiles: ['yellow'], operatingRounds: 2 },
    { name: '3', on: '3', trainLimit: 4, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '3+', on: '3+', trainLimit: 4, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '4', on: '4', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '4+', on: '4+', trainLimit: 3, tiles: ['yellow','green'], operatingRounds: 2 },
    { name: '5', on: '5', trainLimit: 3, tiles: ['yellow','green','brown'], operatingRounds: 2 },
    { name: '6', on: '6', trainLimit: 2, tiles: ['yellow','green','brown'], operatingRounds: 2 },
    { name: '7', on: '7', trainLimit: 2, tiles: ['yellow','green','brown','gray'], operatingRounds: 2 },
    { name: '8', on: '8', trainLimit: 2, tiles: ['yellow','green','brown','gray'], operatingRounds: 2 },
  ],
  trains: [
    { name: '2', distance: 2, price: 100, rustsOn: '4', num: 40 },
    { name: '2+', distance: 2, price: 100, obsoleteOn: '4', num: 5 },
    { name: '3', distance: 3, price: 250, rustsOn: '6', num: 12 },
    { name: '3+', distance: 3, price: 250, obsoleteOn: '6', num: 2 },
    { name: '4', distance: 4, price: 400, rustsOn: '8', num: 8 },
    { name: '4+', distance: 4, price: 400, obsoleteOn: '8', num: 1 },
    { name: '5', distance: 5, price: 600, num: 6 },
    { name: '6', distance: 6, price: 750, num: 5 },
    { name: '7', distance: 7, price: 900, num: 3 },
    { name: '8', distance: 8, price: 1100, num: 99, events: ['signal_end_game'] },
    { name: 'P', distance: 0, price: 200, num: 99, availableOn: '5' },
  ],
  corporations: [
    { sym: 'ATSF', name: 'Atchison, Topeka, and Santa Fe', tokens: [0], color: '#7090c9' },
    { sym: 'B&O', name: 'Baltimore and Ohio Railroad', tokens: [0], color: '#025aaa' },
    { sym: 'C&O', name: 'Chesapeake and Ohio', tokens: [0], color: '#ADD8E6', textColor: '#000' },
    { sym: 'DRG', name: 'Denver and Rio Grande', tokens: [0], color: '#a0522d' },
    { sym: 'GN', name: 'Great Northern Railway', tokens: [0], color: '#87ceeb', textColor: '#000' },
    { sym: 'IC', name: 'Illinois Central Railroad', tokens: [0], color: '#32763f' },
    { sym: 'KCS', name: 'Kansas City Southern Railroad', tokens: [0], color: '#ff0000' },
    { sym: 'MILW', name: 'Milwaukee Road', tokens: [0], color: '#808080' },
    { sym: 'MKT', name: 'Missouri-Kansas-Texas Railroad', tokens: [0], color: '#018471' },
    { sym: 'MP', name: 'Missouri Pacific Railroad', tokens: [0], color: '#4b0082' },
    { sym: 'NYC', name: 'New York Central Railroad', tokens: [0], color: '#110a0c' },
    { sym: 'N&W', name: 'Norfolk and Western Railway', tokens: [0], color: '#8b0000' },
    { sym: 'NP', name: 'Northern Pacific Railway', tokens: [0], color: '#000000' },
    { sym: 'PRR', name: 'Pennsylvania Railroad', tokens: [0], color: '#9acd32', textColor: '#000' },
    { sym: 'SP', name: 'Southern Pacific Railroad', tokens: [0], color: '#f48221' },
    { sym: 'SR', name: 'Southern Railway', tokens: [0], color: '#228b22' },
    { sym: 'SLSF', name: 'St. Louis-San Francisco Railway', tokens: [0], color: '#d02020' },
    { sym: 'TP', name: 'Texas and Pacific Railway', tokens: [0], color: '#800080' },
    { sym: 'UP', name: 'Union Pacific Railroad', tokens: [0], color: '#ffd700', textColor: '#000' },
    { sym: 'WP', name: 'Western Pacific Railroad', tokens: [0], color: '#8b4513' },
  ],

  pregame: [],

  companies: [
    { sym: 'P1', name: 'Lehigh Coal Mine Co.', value: 30, revenue: 0, desc: 'Coal mine marker.' },
    { sym: 'P2', name: 'Fox Bridge Works', value: 40, revenue: 0, desc: '$10 bridge token.' },
    { sym: 'P3', name: 'Reece Oil and Gas', value: 30, revenue: 0, desc: 'Oil marker.' },
    { sym: 'P4', name: 'Hendrickson Iron', value: 40, revenue: 0, desc: 'Ore marker.' },
    { sym: 'P5', name: "Nobel's Blasting Powder", value: 30, revenue: 0, desc: '$15 mountain discount.' },
    { sym: 'P6', name: 'Import/Export Hub', value: 30, revenue: 0, desc: 'Port tile placement.' },
    { sym: 'P7', name: 'Track Engineers', value: 40, revenue: 0, desc: 'Two extra yellow tiles for $20.' },
    { sym: 'P8', name: 'Express Freight Service', value: 40, revenue: 0, desc: 'Extra station marker in red area, +$10 revenue.' },
    { sym: 'P9', name: 'Boomtown', value: 40, revenue: 0, desc: 'Upgrade yellow non-metropolis city to green as free action.' },
    { sym: 'P10', name: 'Carnegie Steel Company', value: 40, revenue: 0, desc: 'Unselected metropolis becomes a metropolis. 5+ players only.' },
    { sym: 'P11', name: 'Pettibone & Mulliken', value: 40, revenue: 0, desc: 'Upgrade two track tiles for $20. One may be one color above phase.' },
    { sym: 'P12', name: 'Standard Oil Co.', value: 60, revenue: 0, desc: 'Two oil markers.' },
    { sym: 'P13', name: 'Pennsy Boneyard', value: 60, revenue: 0, desc: 'Prevent one train from rusting (becomes obsolete instead).' },
    { sym: 'P14', name: 'Pyramid Scheme', value: 60, revenue: 0, desc: 'No special ability.' },
    { sym: 'P15', name: 'Western Land Grant', value: 60, revenue: 0, desc: 'One extra loan at fixed $5 interest.' },
    { sym: 'P16', name: 'Regional Headquarters', value: 60, revenue: 0, desc: 'Upgrade green/brown city after phase 5.' },
    { sym: 'P17', name: 'Great Northern Railway', value: 60, revenue: 0, desc: 'Extra yellow lay on GNR hexes. +$30/$60 route bonus.' },
    { sym: 'P18', name: 'Peabody Coal Company', value: 60, revenue: 0, desc: 'Two coal mine markers.' },
    { sym: 'P19', name: 'Union Switch & Signal', value: 80, revenue: 0, desc: 'Switcher: one train per turn skips over a city.' },
    { sym: 'P20', name: 'Suem & Wynn Law Firm', value: 80, revenue: 0, desc: 'Place station token in full city (cheater token).' },
    { sym: 'P21', name: 'Keystone Bridge Co.', value: 80, revenue: 0, desc: 'Bridge token + one coal or ore marker.' },
    { sym: 'P22', name: 'American Bridge Company', value: 80, revenue: 0, desc: 'Two $10 bridge tokens.' },
    { sym: 'P23', name: 'Bailey Yard', value: 80, revenue: 0, desc: 'Additional station marker for owning corp.' },
    { sym: 'P24', name: 'Anaconda Copper', value: 90, revenue: 0, desc: 'Two ore markers.' },
    { sym: 'P25', name: 'American Locomotive Co.', value: 90, revenue: 0, desc: '10% train discount. Closes on phase 6.' },
    { sym: 'P26', name: 'Rural Junction', value: 90, revenue: 0, desc: 'Three rural junction tiles for empty city hexes.' },
    { sym: 'P27', name: 'Company Town', value: 90, revenue: 0, desc: 'Place Company Town tile; get bonus station. Others pay $10 less.' },
    { sym: 'P28', name: 'Consolidation Coal Co.', value: 90, revenue: 0, desc: 'Three coal mine markers.' },
    { sym: 'P29', name: 'Bankrupt Railroad', value: 120, revenue: 0, desc: 'Free 2-train if starting on No Subsidy tile.' },
    { sym: 'P30', name: 'Double Heading', value: 120, revenue: 0, desc: 'Extender: one non-permanent train runs to one extra city.' },
  ],
}
